// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessoSeletivo_2RP_CodeFirst.Context;

namespace ProcessoSeletivo_2RP_CodeFirst.Migrations
{
    [DbContext(typeof(ProcessoContext))]
    [Migration("20220705024717_CriacaoBanco")]
    partial class CriacaoBanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProcessoSeletivo_2RP_CodeFirst.Domanis.TiposUsuario", b =>
                {
                    b.Property<int>("IdTiposUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdTiposUsuario");

                    b.ToTable("TiposUsuario");

                    b.HasData(
                        new
                        {
                            IdTiposUsuario = 1,
                            UsuarioLogin = "Adiministrador"
                        },
                        new
                        {
                            IdTiposUsuario = 2,
                            UsuarioLogin = "Root"
                        },
                        new
                        {
                            IdTiposUsuario = 3,
                            UsuarioLogin = "Geral"
                        });
                });

            modelBuilder.Entity("ProcessoSeletivo_2RP_CodeFirst.Domanis.Usuarios", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("IdTipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdTipoUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Email = "Admin@email.com",
                            Nome = "Adiministrador",
                            Senha = "Admin",
                            Status = true
                        },
                        new
                        {
                            IdUsuario = 2,
                            Email = "Root@email.com",
                            Nome = "Root",
                            Senha = "Root",
                            Status = true
                        },
                        new
                        {
                            IdUsuario = 3,
                            Email = "Geral@email.com",
                            Nome = "Geral",
                            Senha = "Geral",
                            Status = true
                        });
                });

            modelBuilder.Entity("ProcessoSeletivo_2RP_CodeFirst.Domanis.Usuarios", b =>
                {
                    b.HasOne("ProcessoSeletivo_2RP_CodeFirst.Domanis.TiposUsuario", "tipoUsuario")
                        .WithMany()
                        .HasForeignKey("IdTipoUsuario");

                    b.Navigation("tipoUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
